---
- hosts: proxmox
  gather_facts: true
  become: yes
  roles:
    - role: proxmox_lxc
      when: proxmox_lxc_configure

- hosts: k3s_cluster
  gather_facts: yes
  roles:
    - role: lxc
      become: true
      when: proxmox_lxc_configure
    - role: prereq
      become: true
    - role: download
      become: true
    - role: raspberrypi
      become: true

- hosts: master
  roles:
    - role: k3s_server
      become: true

- hosts: node
  roles:
    - role: k3s_agent
      become: true

- hosts: master
  roles:
    - role: k3s_server_post
      become: true
